version: '2'
services:
    admin-app:
        #文件下载不下来时
        #docker login --username=100006379862 ccr.ccs.tencentyun.com
        #password : videon123
        image: ccr.ccs.tencentyun.com/liujc/meeting:1.0.1
        volumes:
            - ~/res:/home/work/res
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://admin-mysql:3306/voice?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_MONGODB_HOST=192.168.1.111
            - SPRING_REDIS_HOST=192.168.1.111
            - APPLICATION_HOST=192.168.1.111:8090
            - APPLICATION_RES=/home/work/res/
            - APPLICATION_IPCSERVER=192.168.1.111:8383
        ports:
            - 8080:8080
    admin-mysql:
        extends:
            file: mysql.yml
            service: admin-mysql

